sir-ode-python: # Replace with a *short* name that can identify your model in code/URLs
  name: SIR ODE Python # Name of your model, to be displayed in the UI
  origin: Covid Policy Modelling # Name of the organisation responsible for the model, to be displayed in the UI
  enabled: true # Set to false if your repository is private
  imageURL: docker.pkg.github.com/covid-policy-modelling/sir-ode-python-connector/sir-ode-python-connector:latest # URL of your published Docker container
  description: |
    This is a simple example of an SIR model that is run to steady state.
    The final size, the peak infected, and the time of the peak infected is returned, alongside the times and states of the model.
